import express from "express";
import path from "path";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const app = express();
const PORT = Number(process.env.PORT) || 3000;

app.use(express.json());

// Lazy-initialized Gemini client to prevent crash if GEMINI_API_KEY is missing
let aiClient: GoogleGenAI | null = null;

function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY environment variable is required and has not been set in Settings > Secrets.");
    }
    aiClient = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  return aiClient;
}

// REST API endpoint: AI Threat Diagnostics
app.post("/api/gemini/analyze", async (req, res) => {
  const { vin, vehicleModel, logs, context } = req.body;

  try {
    const ai = getGeminiClient();
    const prompt = `
You are the built-in Intelligent Intrusion Detection module of the security operations center (SOC).
You are analyzing a sequence of suspicious CAN-bus messages and system logs generated by a vehicle:
- Vehicle ID (VIN): ${vin}
- Vehicle Model: ${vehicleModel}
- Diagnostic Logs / CAN trace:
${JSON.stringify(logs, null, 2)}
- Operator Context Notes: ${context || "None provided"}

Analyze the provided CAN trace / anomaly log. Perform the following checks:
1. Identify if this resembles a known vulnerability or attack vector (e.g., fuzzing, replay, OBD-II spoofing, DDoS, or telematic payload hijacking).
2. Rank the danger severity level (LOW, MEDIUM, HIGH, CRITICAL).
3. Draft a 16-character hexadecimal CAN mitigating action / whitelist rule payload that could block this on the vehicle's gateway.
4. Provide a super concise 2-sentence visual defense recommendation for the security operator.

Respond strictly in valid JSON format aligning with the schema:
{
  "classification": "Brief name of threat",
  "severity": "LOW" | "MEDIUM" | "HIGH" | "CRITICAL",
  "explanation": "Markdown description outlining the vector.",
  "mitigationHex": "e.g., 0x244: 08 00 CC FF FF 00 00 00",
  "recommendation": "2-sentence short visual recommendation."
}
Only output the raw JSON, do not wrap in markdown codeblocks like \`\`\`json.
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    const text = response.text || "{}";
    res.json(JSON.parse(text));
  } catch (error: any) {
    console.error("Gemini analysis error:", error);
    res.status(500).json({
      error: error.message || "An error occurred during Gemini processing",
      fallback: {
        classification: "Anomalous Command Flooding",
        severity: "HIGH",
        explanation: "AI diagnostic offline, but the rule engine caught a sharp deviation in target node frame frequency, indicating a localized frame injection or diagnostics fuzzing scan.",
        mitigationHex: "0x1A0: 00 00 C1 00 00 00 00 00",
        recommendation: "Activate gateway rate-limiting for diagnostic IDs. Request operator to execute mechanical isolation protocol on Node 7."
      }
    });
  }
});

// REST API endpoint: Threat Advisory Intelligence
app.post("/api/gemini/advisory", async (req, res) => {
  const { topic } = req.body;

  try {
    const ai = getGeminiClient();
    const prompt = `
You are a top automotive cybersecurity research fellow specializing in UNECE R155 regulations and ISO/SAE 21434 compliance.
Provide a quick, authoritative cyber-defense advisory briefing for: "${topic}".
Include:
1. Core risk explanation.
2. Compliance guidance reference points.
3. Solid defensive blueprint actions.

Return a high-quality Markdown response with structured tables, bullet points, and codeblocks of filter rules suitable for an operations HUD briefing. Keep the formatting striking, professional, and dense with content.
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
    });

    res.json({ advisory: response.text || "Advisory details could not be generated." });
  } catch (error: any) {
    console.error("Gemini advisory error:", error);
    res.status(500).json({
      error: error.message || "Could not generate security advisory due to a connection issue.",
      fallback: "### Fallback cyber Advisory:\nAnomalous OTA payload ingestion and unauthenticated firmware flashes present direct risks to cybersecurity compliance under UNECE R155. Operators should strictly enforce active cryptographic signature verification algorithms on all electronic control units (ECUs)."
    });
  }
});

// Proxy GET /api/stats to Flask backend
app.get("/api/stats", async (req, res) => {
  try {
    const response = await fetch("https://canguard-ai-i8sv.onrender.com/api/stats");
    if (!response.ok) {
      throw new Error(`Flask stats returned status ${response.status}`);
    }
    const data = await response.json();
    res.json(data);
  } catch (error: any) {
    console.error("[SYS] Flask stats proxy error:", error.message);
    res.status(502).json({
      error: "Unable to reach Flask backend at https://canguard-ai-i8sv.onrender.com/api/stats",
      details: error.message,
    });
  }
});

// Proxy GET /api/alerts to Flask backend
app.get("/api/alerts", async (req, res) => {
  try {
    const response = await fetch("https://canguard-ai-i8sv.onrender.com/api/alerts");
    if (!response.ok) {
      throw new Error(`Flask alerts returned status ${response.status}`);
    }
    const data = await response.json();
    res.json(data);
  } catch (error: any) {
    console.error("[SYS] Flask alerts proxy error:", error.message);
    res.status(502).json({
      error: "Unable to reach Flask backend at https://canguard-ai-i8sv.onrender.com/api/alerts",
      details: error.message,
    });
  }
});

// Proxy GET /api/traffic to Flask backend
app.get("/api/traffic", async (req, res) => {
  try {
    const response = await fetch("https://canguard-ai-i8sv.onrender.com/api/traffic");
    if (!response.ok) {
      throw new Error(`Flask traffic returned status ${response.status}`);
    }
    const data = await response.json();
    res.json(data);
  } catch (error: any) {
    console.error("[SYS] Flask traffic proxy error:", error.message);
    res.status(502).json({
      error: "Unable to reach Flask backend at https://canguard-ai-i8sv.onrender.com/api/traffic",
      details: error.message,
    });
  }
});

// Setup Vite vs Production static serving
async function initServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[SYS CONTROLLER] Server actively listening on http://0.0.0.0:${PORT}`);
  });
}

initServer();